import type { Metadata } from 'next';
import { Jost } from 'next/font/google';
import './globals.css';

const jostFont = Jost({ subsets: ['latin'], weight: ['400', '500'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${jostFont.className} dark bg-zinc-200 text-zinc-900 antialiased dark:bg-zinc-900 dark:text-zinc-200`}
      >
        {children}
      </body>
    </html>
  );
}
