import './globals.css';
import type { Metadata } from 'next';
import { Jost } from 'next/font/google';

const jostFont = Jost({ subsets: ['latin'], weight: ['400', '500'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${jostFont.className}  antialiased`}>{children}</body>
    </html>
  );
}
